server:
  port: 8080
  tomcat:
    accept-count: 1000
    max-connections: 10000
    max-threads: 800
    min-spare-threads: 100

spring:
  application:
    name: logikm
  datasource:
    kafka-manager:
      jdbc-url: jdbc:mysql://localhost:3306/logikm?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  config: classpath:logback-spring.xml

custom:
  idc: cn
  jmx:
    max-conn: 10 # 2.3版本配置不在这个地方生效
  store-metrics-task:
    community:
      broker-metrics-enabled: true # 社区部分broker metrics信息收集开关, 关闭之后metrics信息将不会进行收集及写DB
      topic-metrics-enabled: true
    didi:
      app-topic-metrics-enabled: false # 滴滴埋入的指标, 社区AK不存在该指标，因此默认关闭
      topic-request-time-metrics-enabled: false
      topic-throttled-metrics: false
    save-days: 7

# 任务相关的开关
task:
  op:
    sync-topic-enabled: false # 未落盘的Topic定期同步到DB中
    order-auto-exec:          # 工单自动化审批线程的开关
      topic-enabled: false      # Topic工单自动化审批开关, false:关闭自动化审批, true:开启
      app-enabled: false        # App工单自动化审批开关, false:关闭自动化审批, true:开启

account:
  ldap:
    enabled: false
    url: ldap://127.0.0.1:389/
    basedn: dc=tsign,dc=cn
    factory: com.sun.jndi.ldap.LdapCtxFactory
    filter: sAMAccountName
    security:
      authentication: simple
      principal: cn=admin,dc=tsign,dc=cn
      credentials: admin
    auth-user-registration: true
    auth-user-registration-role: normal

kcm: # 集群升级部署相关的功能，需要配合夜莺及S3进行使用，这块我们后续专门补充一个文档细化一下，牵扯到kcm_script.sh脚本的修改
  enabled: false # 默认关闭
  s3:
    endpoint: s3.didiyunapi.com
    access-key: 1234567890
    secret-key: 0987654321
    bucket: logi-kafka
  n9e:
    base-url: http://127.0.0.1:8004 # 夜莺任务中心的地址
    user-token: 12345678 # 夜莺用户的token
    timeout: 300 # 集群任务的超时时间，单位秒
    account: root # 集群任务使用的账号
    script-file: kcm_script.sh # 集群任务的脚本

monitor: # 监控告警相关的功能，需要配合夜莺进行使用
  enabled: false
  n9e:
    nid: 2
    user-token: 1234567890
    mon:
      # 夜莺 mon监控服务 地址
      base-url: http://127.0.0.1:8000 # 夜莺v4版本，默认端口统一调整为了8000
    sink:
      # 夜莺 transfer上传服务 地址
      base-url: http://127.0.0.1:8000 # 夜莺v4版本，默认端口统一调整为了8000
    rdb:
      # 夜莺 rdb资源服务 地址
      base-url: http://127.0.0.1:8000 # 夜莺v4版本，默认端口统一调整为了8000

notify:
  kafka:
    cluster-id: 95
    topic-name: didi-kafka-notify
  order:
    detail-url: http://127.0.0.1
